repository: ia/log
favicon: /assets/images/cli.ico

# top left
title: log

# bottom right
description: CC BY-NC-ND 4.0

# bottom left
author: "Ivan Zorin"

# default theme
theme: minima

## local url
#url: http://127.0.0.1:8080/
## global url
url: https://ia.github.io

# base url
base_url: /log

# Social platforms if any
github_username: ia
#linkedin_username:
#rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

plugins:
  - jekyll-redirect-from

# Date format for timestamps in posts
minima:
  date_format: "%Y.%m.%d"

# Minima: custom header links - order matters!
header_pages:
  - _pages/frontpage.md
  - _pages/archive.md
  - _pages/source.md
  - _pages/about.md

include:
    - _pages
    - favicon.ico

exclude:
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Alternative and extended markdown flavor
#kramdown:
#  syntax_highlighter: rouge
#  input: GFM

