# repo user/name
repository: ia/log

# favicon auto variable
favicon: /assets/images/cli.ico

# top left
title: log

# bottom right // overridden manually
description: CC BY-NC-ND 4.0

# author auto tagging
author: ia

# default theme
theme: minima

# site url
url: https://ia.github.io

# base url on site
base_url: /log

# gh account
github_username: ia

# minima: show excerpts in the frontpage
show_excerpts: true

plugins:
  - jekyll-redirect-from

# date format for timestamps in posts
minima:
  date_format: "%Y.%m.%d @ <i>%H:%M</i>"

# minima: custom header links in the top right corner, order matters!
header_pages:
  - _pages/main.md
  - _pages/posts.md
  - _pages/rss.md

# list of files to be copied into / on-site
include:
  - _pages
  - LICENSE

# list of files to ignore
exclude:
  - .gitignore
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - TODO.md
  - _posts/00template.md

